- name: playbook
  hosts: all
  become: true
  vars:
    deployment_path: "/home/ubuntu/app"
    compose_path: "./docker-compose.yaml"
  roles:
    - role: geerlingguy.docker
      version: "4.1.3"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600 # One day

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        name:
          - docker<7.0
          - docker-compose
          - requests==2.31.0

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ deployment_path }}"
        state: directory

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "{{ compose_path }}"
        dest: "{{ deployment_path }}"

    - name: Run `docker-compose up`
      docker_compose:
        project_src: "{{ deployment_path }}"
      environment:
        FRONTEND_IMAGE: "{{ lookup('env','FRONTEND_IMAGE') }}"
        BACKEND_IMAGE:  "{{ lookup('env','BACKEND_IMAGE') }}"
